name: 'Semver Tags'
description: 'Gets the previous semver tag and calculates the next version.'
branding:
  icon: 'arrow-up-circle'
  color: 'gray-dark'
inputs:
  GITHUB_TOKEN:
    description: The github token.
    required: true
  tag-prefix:
    description: 'A value prefixed to the version number when tagging the repo.'
    required: false
    default: ''
  incremented-value:
    description: 'What value should be incremented?'
    required: false
    default: patch
  default-ref:
    description: 'The value for the repos default ref'
    required: false
    default: refs/heads/main
outputs:
  previous-version:
    description: 'The previous version isolated by the action'
  semantic-version:
    description: 'The calculated version number.'
  core-version: 
    description: 'The core version part of the semantic version.'
  version-tag: 
    description: 'The complete tag for the calculated version'
runs:
  using: 'node12'
  main: 'dist/index.js'
